### ISSUE TITLE
升级插件 下载失败。 Method Not Allowed

### ISSUE THREAD

**Issue by lei-mu** [WenPai-org/wp-china-yes#117]
升级插件
正在从 http://d.w.org.ibadboy.net/plugin/limit-login-attempts-reloaded.2.25.25.zip 下载更新…

下载失败。 Method Not Allowed

-----
https://a2.wp-china-yes.net/WordPress@6.3.2/wp-includes/js/jquery/jquery.min.js?ver=3.7.0
https://a2.wp-china-yes.net/WordPress@6.3.2/wp-includes/js/jquery/jquery-migrate.min.js?ver=3.4.1
https://a2.wp-china-yes.net/WordPress@6.3.2/wp-includes/js/dist/vendor/wp-polyfill-inert.min.js?ver=3.1.2
...

get 405

---------

单独访问  {"code":"40510001","msg":"invisible bucket"}

-----

本人不确定升级插件失败这个错误和wp-china-yes 相关，看到控制台的 405 所以问问

**Comment by zx900930** [comment]
服务器挂了，建议暂时先上正向代理顶一顶

**Comment by devhaozi** [comment]
使用 v3.6.1 版本
