### ISSUE TITLE
[Bug Report]: 

### ISSUE THREAD

**Issue by rydensun** [WenPai-org/wp-china-yes#118]
### 在提问之前 (Before asking)

- [X] 我已经搜索了现有的 Issues 和 Discussions (I've searched the existing Issues and Discussions)
- [X] 我已经阅读了 README 中除版本记录以外的所有内容 (I've read everything in the README except the version notes)
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备 (I spend at least 5 minutes thinking and preparing before asking a question)
- [X] 这个问题出现在最新版的 WP-China-Yes 上 (This question appears on the latest version of WP-China-Yes)
- [ ] 我使用过旧版的 WP-China-Yes 并且没有出现这个问题 (I've used an older version of WP-China-Yes and didn't have this problem)
- [X] 这个问题出现了至少 3 次 (This question has occurred at least 3 times)

### 描述问题 (Describe the problem)

安装之后，theme preview 仍旧是 429

### 预期行为 (Expected behavior)

可以正常预览 theme

### 如何复现 (How to reproduce)

1. 安装 WP-China-Yes
2. 保存了默认设置
3. 启动并开启了自动更新
4. 刷新页面之后，还是显示 429

### 截图 (Screenshots)

![screenshot-20240426-215700](https://github.com/WenPai-org/wp-china-yes/assets/10702116/e6212a19-615e-42cc-ab91-656e71459d44)

### 还有别的吗 (Anything else)

WordPress 版本6.5.2

**Comment by f2010525** [comment]
主题预览的域名是 wp-themes.com 需要单独处理，429 的问题可能与你的地域网络环境有关，我这边没能复现，后续会考虑将预览域名替换为 wpthemes.cn  或者别的来加速。

目前核心的功能之一，后台去广告的功能在开发中，将会在下个版本中统一处理。

**Comment by devhaozi** [comment]
这部分插入的链接域名是硬编码在 wp 核心中的，无解。
